cultuurnet/jwt-provider

README.md
app/Console/AbstractCommand.php
app/Console/DecodeJwtCommand.php
app/Console/GenerateJwtCommand.php
app/Jwt/JwtServiceProvider.php
bin/app.php
bootstrap.php
composer.json
composer.lock
config.dist.yml

This reverts commit b9cdefbf3e59f4861eef0d680c3e6a1168945b50.

Revert "Revert "Feature/iii 886""

---

app/ActionServiceProvider.php

See commit message for explanation.

Bugfix: Cannot handle token prior to x

---

app/ActionServiceProvider.php
src/Domain/Action/RequestToken.php
src/Domain/Enum/Locale.php
src/Domain/Service/LoginServiceInterface.php
src/Infrastructure/Service/ExtractLocaleFromRequest.php
src/Infrastructure/Service/LoginAuth0Adapter.php
tests/Domain/Action/RequestTokenTest.php
tests/Domain/Service/ExtractLocaleFromRequestTest.php
tests/Infrastructure/Service/LoginAuth0AdapterTest.php

- logic to pass the language preference to auth0 when logging in

Feature: III 3235

---

composer.json
composer.lock

- downgraded package monolog/monolog
- downgraded package symfony/inflector

Downgrade symfony/inflector and monolog/monolog

---

.github/pull_request_template.md
.github/workflows/ci.yml
.travis.yml
composer.json
composer.lock

- Fixed not being able to install composer dependencies on PHP 7.1
- Changed Travis integration to Github Actions to make sure we test on the right PHP version(s)

Fix incompatible php dependency

---

src/Infrastructure/Service/LoginAuth0Adapter.php
tests/Infrastructure/Service/LoginAuth0AdapterTest.php

- ui_locales to locale
---
Ticket: https://jira.uitdatabank.be/browse/III-3682

III-3682 - Change ui_locales to locale

---

.github/workflows/ci.yml
app/ActionServiceProvider.php
composer.json
composer.lock
phpstan.neon
src/Domain/Action/RequestLogout.php
src/Domain/Action/RequestToken.php
src/Infrastructure/Error/SentryExceptionHandler.php
src/Infrastructure/Service/CultureFeedDecorator.php
src/Infrastructure/Service/ExtractClientInformationFromRequest.php
src/Infrastructure/Service/IsAllowedRefreshToken.php
tests/Domain/Action/RequestTokenTest.php

- Added PHPStan to the CI pipeline.
**Note**: Although not directly related to the PHP-CS-Fixer I noticed various type hints were wrong.
---
Ticket: https://jira.uitdatabank.be/browse/III-3775

III-3775 Add PHPStan

---

.github/workflows/ci.yml

- Remove PHP extensions from GitHub Actions

Remove PHP extensions from GitHub Actions

---

composer.json
composer.lock

- Update udb3-api-guard with dependencies which also updates value objects
---
Ticket: https://jira.uitdatabank.be/browse/III-3842

III-3842 Update udb3-api-guard with related dependencies

---

app/ActionServiceProvider.php
app/ApiGuardServiceProvider.php
app/BaseServiceProvider.php
app/MiddlewareServiceProvider.php
app/RoutingServiceProvider.php
app/SentryServiceProvider.php
app/SessionServiceProvider.php
phpstan.neon
src/Domain/Exception/NoDestinationPresentException.php
src/Infrastructure/Error/ExceptionHandler.php
src/Infrastructure/Error/SentryExceptionHandler.php
src/Infrastructure/Service/CultureFeedDecorator.php
tests/Domain/Action/LogOutTest.php
tests/Domain/Action/RefreshTest.php
tests/Domain/Action/RequestLogoutTest.php
tests/Domain/Service/ExtractLocaleFromRequestTest.php
tests/Domain/Service/GenerateAuthorizedDestinationUrlTest.php
tests/Infrastructure/Factory/SlimResponseFactoryTest.php
tests/Infrastructure/Middleware/AllowedRefreshTest.php
tests/Infrastructure/Service/ExtractClientInformationFromRequestTest.php
tests/Infrastructure/Service/IsAllowedRefreshTokenTest.php
tests/Infrastructure/Service/LogOutAuth0AdapterTest.php
tests/Infrastructure/Service/LoginAuth0AdapterTest.php

- Bumped phpstan to level 7
- Also run phpstan checks in `app/`

Phpstan level 7

---

.github/dependabot.yml
composer.lock

- Add dependabot version update config file
---
Ticket: https://jira.uitdatabank.be/browse/III-3854

III-3854 Enable dependabot version updates

---

composer.json
composer.lock

- Remove unused `symfony/console`

Remove unused `symfony/console`

---

app/ActionServiceProvider.php
config.dist.yml

- `referrer` to auth0 instance
---
Ticket: https://jira.uitdatabank.be/browse/UID-761

UID-761 - Add referrer to auth0 instance

---

app/ActionServiceProvider.php
config.dist.yml
src/Infrastructure/Service/LoginAuth0Adapter.php
tests/Infrastructure/Service/LoginAuth0AdapterTest.php

- Fixed custom `referrer` parameter not being passed to the login
---
Ticket: https://jira.uitdatabank.be/browse/III-4086
The actual background image might need some tweaking to make it fit better.

III-4086 Fix referrer

---

src/Domain/Enum/Locale.php
src/Infrastructure/Service/ExtractLocaleFromRequest.php
tests/Domain/Service/ExtractLocaleFromRequestTest.php

- german locale
---
Ticket: https://jira.uitdatabank.be/browse/III-4348

III-4348 - 🇩🇪 Add german locale

---

src/Infrastructure/Service/LoginAuth0Adapter.php
tests/Infrastructure/Service/LoginAuth0AdapterTest.php

- Added `skip_verify_legacy` and `product_display_name` parameters
---
Ticket: https://jira.uitdatabank.be/browse/III-4506

III-4506 Fix account linking step for existing accounts in UDB

---

Jenkinsfile.uitidv1
lib/tasks/jwt-provider-uitidv1/build.rake
lib/tasks/jwt-provider-uitidv1/build_artifact.rake

New jenkinsfile and rake task to build the jwt-provider-uitidv1 (legacy)
---
Ticket: III-5060

New jenkinsfile and rake tasks for jwt-provider-uitidv1

---

Makefile
docker-compose.yml
docker/php/Dockerfile

Added a docker file, to help with the PHP 8 migration.
Currently the PHP version is PHP 7.4, like the server.
---
Ticket: https://jira.publiq.be/browse/III-6082

III-6082 Added docker file

---

app/Error/ApiExceptionHandler.php
app/Factory/ErrorHandlerFactory.php
composer.json
composer.lock

Replaced php-http/message-factory with laminas/laminas-httphandlerrunner 
---
Ticket: Ticket: https://jira.publiq.be/browse/III-6082

III-6082 Replaced php-http/message-factory with laminas/laminas-httphandlerrunner

---

composer.json
composer.lock

Very very tiny pr :-)
Upgrade composer to php 7.4
---
Ticket: https://jira.publiq.be/browse/III-6117

III-6117 Upgrade composer to php 7.4

---

.gitignore
Makefile
app/CommandServiceProvider.php
app/Console/DecodeJwtCommand.php
app/Console/EncodeJwtCommand.php
app/CultureFeed/CultureFeedServiceProvider.php
app/Jwt/JwtServiceProvider.php
app/OAuth/OAuthServiceProvider.php
app/RequestTokenStorage/RequestTokenStorageServiceProvider.php
app/RoutingServiceProvider.php
composer.json
composer.lock
docker-compose.yml
docker/php/Dockerfile
docker/php/xdebug.ini
phpstan.neon
rector.php
src/CultureFeed/CultureFeedFactory.php
src/Jwt/JwtOAuthCallbackHandler.php
src/OAuth/OAuthController.php
src/OAuth/OAuthUrlHelper.php
src/RequestTokenStorage/RequestTokenSessionStorage.php
src/User/CultureFeedUserService.php
src/User/UserClaims.php
tests/Jwt/JwtOAuthCallbackHandlerTest.php
tests/OAuth/OAuthUrlHelperTest.php
tests/RequestTokenStorage/RequestTokenSessionStorageTest.php
tests/User/CultureFeedUserServiceTest.php
tests/User/UserClaimsTest.php

Preperation to migrate uitidv1 to PHP 7.4/PHP 8.0.
- Added a docker file
- Added a makefile
- Update the composer file with some extra code quality tools (phpstan and rector).
The current code does NOT pass any of the code quality checks I added, those will be fixed in following PRs.
At that point I will also add these checks in the pipeline of github.

Uitidv1 - Modernise dev dependencies

---

composer.json
composer.lock

Upgrade slim/psr7
---
Ticket: https://jira.publiq.be/browse/III-6082

Upgrade slim/psr7

---

composer.json
composer.lock

Upgrade filp/whoops
---
Ticket: https://jira.publiq.be/browse/III-6082

Upgrade filp/whoops

---

composer.json
composer.lock
web/index.php

Replace zendframework/zend-httphandlerrunner with laminas/laminas-http-handlerrunner
---
Ticket: https://jira.publiq.be/browse/III-III-6082

III-6082 Replace zend-httphandlerrunner with laminas-http-handlerrunner

---

.github/workflows/ci.yml
.gitignore
app/Error/SentryHandlerScopeDecorator.php
app/Error/SentryHubServiceProvider.php
composer.json
composer.lock
docker-compose.yml

- Added PHP 8.1 to CI pipeline
- Upgraded `publiq/php-cs-fixer-config` for PHP 8.1 support
- Removed deprecated version header of docker-compose file
---
Ticket: https://jira.publiq.be/browse/III-5031

III-5031 Support PHP 8.1

---

.github/workflows/ci.yml
app/CultureFeed/CultureFeedServiceProvider.php
app/OAuth/OAuthServiceProvider.php
composer.json
composer.lock
docker/php/Dockerfile
docker/php/apache-limits.conf
src/Auth/AuthorizeOptions.php
src/Auth/AuthorizeOptionsQueryString.php
src/Auth/ConsumerCredentials.php
src/Auth/TokenCredentials.php
src/Auth/User.php
src/CultureFeed/CultureFeedFactory.php
src/CultureFeed/CultureFeedFactoryInterface.php
src/Jwt/JwtOAuthCallbackHandler.php
src/OAuth/OAuthCallbackHandlerInterface.php
src/OAuth/OAuthController.php
src/OAuth/OAuthService.php
src/OAuth/OAuthUrlHelper.php
src/RequestTokenStorage/RequestTokenSessionStorage.php
src/RequestTokenStorage/RequestTokenStorageInterface.php
src/User/CultureFeedUserService.php
src/User/UserServiceInterface.php
tests/Jwt/JwtOAuthCallbackHandlerTest.php
tests/OAuth/OAuthUrlHelperTest.php
tests/RequestTokenStorage/RequestTokenSessionStorageTest.php
tests/User/CultureFeedUserServiceTest.php
web/jwt-example-2.php
web/jwt-example-v1.php

- Included Auth package code internally to ease PHP 8 upgrade
---
Ticket: https://jira.publiq.be/browse/III-6738

III-6738 Include Auth package code
